<?php
/**
 * @file
 * Install, update and uninstall functions for the blogifier install profile.
 */

/**
 * Implements hook_install().
 *
 * Perform actions to set up the site for blogifier.
 *
 * @see system_install()
 */
function blogifier_install() {
  // First, do everything in standard profile.
  include_once DRUPAL_ROOT . '/core/profiles/standard/standard.install';
  standard_install();
  
  // More code in here to make nodes, terms, etc !!!
}
